"""_1_modify_product_fields_types

Revision ID: 25f1d223fdf7
Revises: a544b70486c2
Create Date: 2022-05-16 14:34:00.936544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25f1d223fdf7'
down_revision = 'a544b70486c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'uniq_id_product',
                    existing_type=sa.TEXT(),
                    nullable=False)
    op.alter_column('product', 'visible',
                    existing_type=sa.INTEGER(),
                    type_=sa.BOOLEAN(),
                    nullable=False,
                    postgresql_using="visible::boolean",)
    op.alter_column('product', 'removed',
                    existing_type=sa.INTEGER(),
                    type_=sa.BOOLEAN(),
                    nullable=False,
                    postgresql_using="removed::boolean",)
    op.alter_column('product', 'id_product_type',
                    existing_type=sa.TEXT(),
                    type_=sa.INTEGER(),
                    nullable=False,
                    postgresql_using="id_product_type::integer",)
    op.alter_column('product', 'product_price',
                    existing_type=sa.TEXT(),
                    type_=sa.FLOAT(),
                    nullable=False,
                    postgresql_using="product_price::double precision",)
    op.create_unique_constraint("uniq_id_product", 'product', ['uniq_id_product'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uniq_id_product", 'product', type_='unique')
    op.alter_column('product', 'removed',
                    existing_type=sa.BOOLEAN(),
                    type_=sa.INTEGER(),
                    nullable=True,
                    postgresql_using="removed::integer",)
    op.alter_column('product', 'visible',
                    existing_type=sa.BOOLEAN(),
                    type_=sa.INTEGER(),
                    nullable=True,
                    postgresql_using="visible::integer",)
    op.alter_column('product', 'uniq_id_product',
                    existing_type=sa.TEXT(),
                    nullable=True,)
    op.alter_column('product', 'id_product_type',
                    existing_type=sa.INTEGER(),
                    type_=sa.TEXT(),
                    nullable=False,
                    postgresql_using="id_product_type::text",)
    op.alter_column('product', 'product_price',
                    existing_type=sa.FLOAT(),
                    type_=sa.TEXT(),
                    nullable=False,
                    postgresql_using="product_price::text",)
    # ### end Alembic commands ###
