"""Initial migration.

Revision ID: a544b70486c2
Revises:
Create Date: 2022-05-13 18:32:46.740901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a544b70486c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('uniq_id_product', sa.Text(), nullable=True),
                    sa.Column('product_name', sa.Text(), nullable=True),
                    sa.Column('product_price', sa.Text(), nullable=True),
                    sa.Column('id_product_type', sa.Text(), nullable=True),
                    sa.Column('product_type', sa.Text(), nullable=True),
                    sa.Column('id_category', sa.Text(), nullable=True),
                    sa.Column('category_name', sa.Text(), nullable=True),
                    sa.Column('category1', sa.Text(), nullable=True),
                    sa.Column('category2', sa.Text(), nullable=True),
                    sa.Column('tax_name', sa.Text(), nullable=True),
                    sa.Column('place_send_name', sa.Text(), nullable=True),
                    sa.Column('visible', sa.Integer(), nullable=True),
                    sa.Column('removed', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('service',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('company', sa.String(length=30), nullable=True),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('CA', sa.Float(), nullable=True),
                    sa.Column('solid', sa.Float(), nullable=True),
                    sa.Column('liquid', sa.Float(), nullable=True),
                    sa.Column('majoration', sa.Float(), nullable=True),
                    sa.Column('graph_url', sa.Text(), nullable=True),
                    sa.Column('top_liquids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('all_products_list_by_name', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('all_products_timeline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('concert', sa.Text(), nullable=True),
                    sa.Column('concert_infos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=100), nullable=True),
                    sa.Column('password', sa.String(length=100), nullable=True),
                    sa.Column('name', sa.String(length=20), nullable=True),
                    sa.Column('company', sa.String(length=30), nullable=True),
                    sa.Column('super_user', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('service')
    op.drop_table('product')
    # ### end Alembic commands ###
